SmartLearn/CabinetApp/urls.py
from django.urls import path
from .views import get_events, cabinets_view, update_calend, user_full, user_full_view, VideoArchView

app_name = 'cabinet'


urlpatterns = [
    path('get_events/<int:cabinet_id>/', get_events, name='get_events'),
    path('cabinets/<int:cab_id>/', cabinets_view, name='cabinet'),
    path('get_updates/<int:cabinet_id>/', update_calend, name='get_update'),
    path('userfull_info_cab/<int:cabinet_id>/', user_full, name='userfull_info_cab'),
    path('userfull_detailed/<int:post_id>/', user_full_view, name='userfull_detailed'),
    path('records_cab/<int:cabinet_id>/', VideoArchView.as_view(), name='records_cab')
]

SmartLearn/ChatApp/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path('', views.chat, name="chat"),
    path("<int:chat_id>/", views.room, name="room"),
    path('create_chat_d/<int:another_user_id>/', views.create_chat_dialog, name="create_chat"),
]

SmartLearn/ProfileApp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import sort_category, blog, logining, UserRegisterViews, logout, profilusercabinet, delete_post, \
    edit_service, users_list, publish_post, delete_service, sevices_pay, post_detailed, \
    delete_basket, ProfileUserView, DeleteView, ProfileServices, ServiceOrderView, PaysView

app_name = 'profile'

urlpatterns = [
    path('tag/<int:tag_id>/', sort_category, name='tag'),
    path('blog/<int:user_id>/', blog, name='blog'),
    path('post_detailed/<int:post_id>/', post_detailed, name='post_detailed'),
    path('login/', logining, name='login'),
    path('register/', UserRegisterViews.as_view(), name='register'),

    path('logout/', logout, name='logout'),
    path('profils/<int:user_id>/', ProfileUserView.as_view(), name='updateViews'),
    path('profils/cabinet/<int:user_id>/', profilusercabinet, name='profile_cabinet'),
    path('delete_post/<int:post_id>/', delete_post, name='delete_post'),
    path('services/', ProfileServices.as_view(), name='services'),
    path('edit_serv/<int:service_id>/', edit_service, name='edit_service'),
    path('delete_service/<int:service_id>/', delete_service, name='delete_serv'),
    path('users/', users_list, name='users_list'),
    path('publish/', publish_post, name='publish_post'),
    path('pay_service/<int:service_id>/', sevices_pay, name='pay_service'),
    path('pays/', PaysView.as_view(), name='pays'),
    path('services_pay/', ServiceOrderView.as_view(), name='services_pay'),
    path('delete_bask/<int:basket_id>/', delete_basket, name='delete_bask'),
    path('delete_cab/<int:cabinet_id>/', DeleteView.as_view(), name='delete_cab'),
]

SmartLearn/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProfileApp.views import IndexView



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('cabinet/', include('CabinetApp.urls', namespace='сabinet')),
    path('profile/', include('ProfileApp.urls', namespace='profile')),
    path("chat/", include("ChatApp.urls")),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SmartLearn/SmartLearn/urls.py
from django.contrib import admin
from django.urls import path, include
from SmartLearn.Learn.views import *

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('Learn.urls', namespace='Learn')),
]

SmartLearn/ProfileApp/views.py
from http.client import HTTPResponse
from django.http import JsonResponse, HttpRequest, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from CabinetApp.models import Schedule, Cabinet
from ProfileApp.forms import UserForm, UserRegisterForm, CabinetForm, BlogForm, ServiceForm, CabinetTransferForm, UserProfileForm
from ProfileApp.models import Teacher, User, Tag, Post, EmailVerification, Service, Students, Baskets
# from Cabinet.models import Schedule
from django.contrib import auth
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.db.models import Prefetch, Count
from django.db import transaction
from django.core.cache import cache
from icecream import ic


class IndexView(View):

    def get(self, request: HttpRequest) -> render:
        if request.user.is_authenticated:
            bas_quant = Baskets.objects.filter(user=request.user).total_quantity()
        else:
            bas_quant = 0

        context = {
            'title': 'Список учителей',
            'users': User.objects.prefetch_related('teacher'),
            'regis': request.user,
            'autentic': request.user.is_authenticated,
            'categories': Tag.objects.all(),
            'bas_quant': bas_quant,
        }
        return render(request, 'profileapp/profile/index_start.html', context=context)


def sort_category(request: HttpRequest, tag_id: int = None) -> render:
    if request.user.is_authenticated:
        bas_quant = Baskets.objects.filter(user=request.user).total_quantity()
    else:
        bas_quant = 0
    categories = Tag.objects.all()
    if tag_id:
        users = ic(User.objects.filter(teacher__tags__id=tag_id).prefetch_related('teacher'))
    else:
        users = User.objects.select_related('teacher').prefetch_related('teacher')
    context = {
        'users': users,
        'categories': categories,
        'title': 'Список учителей',
        'regis': request.user,
        'autentic': request.user.is_authenticated,
        'bas_quant': bas_quant,
    }
    return render(request, 'profileapp/profile/index_start.html', context=context)


def blog(request: HttpRequest, user_id: int) -> render:
    user = User.objects.get(id=user_id)
    teach = False
    teacher = user.teacher
    if request.user.is_authenticated:
        bas_quant = Baskets.objects.filter(user=request.user).total_quantity()
    else:
        bas_quant = 0
    if user == request.user:
        teach = True
    context = {
        'title': 'Блог',
        'user_auth': user,
        'autentic': request.user.is_authenticated,
        'teach': teach,
        'posts': Post.objects.filter(teacher=teacher, is_private=False).order_by('-date_create'),
        'prices': Service.objects.filter(teacher=teacher),
        'bas_quant': bas_quant,
    }
    return render(request, 'profileapp/profile/new_blog_page.html', context=context)


def logining(request):
    if request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, 'Неверный логин или пароль')
        else:
            messages.error(request, 'Неверный логин или пароль')
    else:
        form = UserForm()
    context = {
        'title': 'Авторизация',
        'form': form,
    }
    return render(request, 'profileapp/profile/login.html', context=context)


class UserRegisterViews(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'profileapp/profile/register.html'
    success_url = reverse_lazy('profile:login')

    def form_valid(self, form):
        is_teacher = form.cleaned_data['is_teacher']
        user = form.save(commit=False)

        if is_teacher:
            user.is_teacher = True
            teacher = Teacher.objects.create(description='')
            ic(teacher)
            user.teacher = teacher
            ic(user.teacher)
            teacher.user_teacher = ic(user)
            ic(teacher.user_teacher)
        else:
            user.is_student = True
        user.save()
        if user.is_student:
            with transaction.atomic():
                Students.objects.create(user=user)
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(UserRegisterViews, self).get_context_data(**kwargs)
        return context


class ProfileUserView(View):
    def get(self, request: HttpRequest, user_id: int) -> render:
        form = UserProfileForm(instance=request.user)
        status = None
        if request.user.id:
            pers = User.objects.get(id=request.user.id).is_authenticated
            user = User.objects.get(id=user_id)
            if user.is_teacher:
                status = 'teacher'
            else:
                status = 'student'
        else:
            pers = False

        context = {
            'title': 'Профиль',
            'user': User.objects.get(id=user_id),
            'autentic': pers,
            'teacher': User.objects.select_related('teacher').get(id=user_id),
            'status': status,
            'form': form,
        }
        print(status)
        return render(request, 'profileapp/profile/profile.html', context=context)

    def post(self, request: HttpRequest, user_id: int) -> render:
        form = UserProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile:updateViews', kwargs={'user_id': user_id}))
        else:
            return HttpResponseRedirect(reverse('profile:updateViews', kwargs={'user_id': user_id}))


def profilusercabinet(request: HttpRequest, user_id: int) -> render:
    if request.method == 'POST':
        teacher = Teacher.objects.get(user_teacher=user_id)
        form = CabinetForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            student = form.cleaned_data['users']
            cabinet = Cabinet.objects.create(name=name, teacher=teacher)
            cabinet.users.set(student)
            return HttpResponseRedirect(reverse('profile:profile_cabinet', kwargs={'user_id': user_id}))

    if request.user.id:
        pers = User.objects.get(id=request.user.id).is_authenticated
    else:
        pers = False
    user = User.objects.get(id=user_id)
    teacher = None
    cabinets = None

    if user.is_teacher:
        teacher = Teacher.objects.get(user_teacher=user)
        cabinets = Cabinet.objects.filter(teacher=teacher)
    else:
        # Пользователь - студент, найдите связанных преподавателей и кабинеты
        student = Students.objects.get(user=user)
        teacher = student.teacher
        cabinets = Cabinet.objects.filter(users=user)

    users_by_cabinet = {}
    for cabinet in cabinets:
        users = list(cabinet.users.all())
        users.sort(key=lambda user: (user.is_teacher, user.username))
        users_by_cabinet[cabinet] = users

    print(users_by_cabinet)
    context = {
        'title': 'Кабинеты',
        'teach': 'teahs',
        'autentic': pers,
        'users_by_cab': users_by_cabinet,
        'form': CabinetForm(),
    }
    return render(request, 'profileapp/profile/profile_cabinet.html', context=context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def delete_post(request, post_id):
    Post.objects.filter(id=post_id).delete()
    return HttpResponseRedirect(reverse_lazy('profile:blog', args=(request.user.id,)))


class ProfileServices(View):
    def get(self, request):
        if request.user.id:
            pers = User.objects.get(id=request.user.id).is_authenticated
        form = ServiceForm()
        user_t = request.user.teacher
        service = Service.objects.filter(teacher=user_t)
        print(service)
        context = {
            'service': service,
            'autentic': pers,
            'form': form,
        }
        return render(request, 'profileapp/profile/services.html', context=context)

    def post(self, request: HttpRequest) -> render:
        form = ServiceForm(request.POST)
        if form.is_valid():
            servis = Service.objects.create(
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description'],
                user_count=form.cleaned_data['user_count'],
                price=form.cleaned_data['price'],
                teacher=User.objects.get(id=request.user.id).teacher,
            )
            servis.save()
            if Tag.objects.filter(name=form.cleaned_data['name']).exists():
                tag = Tag.objects.get(name=form.cleaned_data['name'])
                tag.teachers.add(User.objects.get(id=request.user.id).teacher)
            else:
                tag = Tag.objects.create(name=form.cleaned_data['name'])
                tag.teachers.add(User.objects.get(id=request.user.id).teacher)
            return HttpResponseRedirect(reverse('profile:services'))


def edit_service(request, service_id):
    services = Service.objects.get(id=service_id)

    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=services)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile:services'))
    else:
        form = ServiceForm(instance=services)
    context = {
        'form': form,
        'service_id': service_id,
    }

SmartLearn/ProfileApp/templates/profileapp/profile/base_index_blog.html
{% load static %}

<!DOCTYPE html>
<html  >

<head>
  <!-- Site made with Mobirise Website Builder v5.9.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.9.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <meta name="description" content="">

  <style>
    /* Ваши стили для матового эффекта */
    .navbar {
        background-color: rgba(255, 255, 255, 0.5); /* Задайте фон с непрозрачностью */
        backdrop-filter: blur(10px); /* Матовый эффект */
    }

    .navbar a {
        color: #333; /* Цвет ссылок */
    }
  </style>
{% block styles %}{% endblock %}
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css_nice/nicepage.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css_nice/главная.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
</head>

<body>
  <section data-bs-version="5.1" class="menu menu1 cid-tT4YwksE3n" once="menu" id="menu01-0">


	<nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
		<div class="container">
			<div class="navbar-brand">
				<span class="navbar-caption-wrap"><a class="navbar-caption text-black display-4" href="{% url 'index' %}">Главная</a></span>
			</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<div class="hamburger">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</div>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
					<li class="nav-item">
						<a class="nav-link link text-black display-4" href="#">О нас</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-black display-4" href="#" aria-expanded="false">Прайс</a>
					</li>
{#					<li class="nav-item">#}
{#						<a class="nav-link link text-black display-4" href="#">Контакты</a>#}
{#					</li>#}
                    {% if autentic %}
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" href="{% url 'chat:chat' %}"> Чат</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link link text-black display-4" href="{% url 'profile:logout' %}"> Выход</a>
                        </li>

                        {% if user.is_student %}
                        	<li class="nav-item">
                                <a class="nav-link link text-black display-4" href="{% url 'profile:services_pay' %}">
                                    Услуги
                                    <span class="badge badge-primary rounded-circle">{{ bas_quant }}</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" href="{% url 'profile:updateViews' user.id %}"> Профиль</a>
                        </li>
                    {% endif %}
				</ul>
                {% if not autentic %}
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-primary display-4" href="{% url 'profile:login' %}"> Вход</a>
                    </div>
                {% endif %}
			</div>
		</div>
	</nav>
</section>
<body>
{% block content %}
{% endblock %}
</body>

</html>

SmartLearn/ProfileApp/templates/profileapp/profile/new_blog_page.html
{% extends 'profileapp/profile/base_index_blog.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}


{% block content %}



    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row justify-content-center" style="max-width: 100%; height: auto;">
            <div class="col-12 col-md-12 col-lg-5 image-wrapper">
                <img class="w-100" src="{% if user_auth.images %}{{ user_auth.images.url }}{% else %}{% static 'image/profile_img/img.png' %}{% endif %}" alt="Mobirise Website Builder">
            </div>
            <div class="col-12 col-md-12 col-lg">
                <div class="text-wrapper align-left">
                    <h1 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                        <strong>{{ user_auth.last_name }}</strong>
                    </h1>
                    <h1 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                        <strong>{{ user_auth.first_name }}</strong>
                    </h1>
                    <p class="mbr-text align-left mbr-fonts-style mb-4 display-7">
                        {{ user_auth.teacher.description }}
                    </p>
                    <p class="mbr-text align-left mbr-fonts-style mb-4 display-7">
                        Телефон для связи: {{ user_auth.teacher.user_teacher.phone_number }}
                    </p>
                    <p class="mbr-text align-left mbr-fonts-style mb-4 display-7">
                        Email для связи: {{ user_auth.teacher.user_teacher.email }}
                    </p>
                    {% if autentic %}
                    	<div class="mbr-section-btn align-left mt-3">
                            <a class="btn btn-success-outline display-7" href="{% url 'chat:create_chat' user.id %}">Написать сообщение</a>
                        </div>
                    {% else %}
                        <div class="mbr-section-btn align-left mt-3">
                            <a class="btn btn-success-outline display-7" href="{% url 'profile:login' %}">Написать сообщение</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </section>

    <div class="container">
        <section class="u-align-center u-clearfix u-grey-5 u-section-2" id="carousel_563d">
            <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
                <div class="data-layout-selected u-clearfix u-expanded-width u-gutter-20 u-layout-wrap u-layout-wrap-1">
                    <div class="u-layout">
                        <div class="u-layout-row" style="">
                            {% for price in prices %}
                                {% if price.users.count < price.user_count %}
                                    <div class="u-align-center u-container-style u-layout-cell u-left-cell u-shape-rectangle u-size-20 u-white u-layout-cell-1">
                                        <div class="u-container-layout u-valign-top u-container-layout-1">
                                            <h4 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-4-base u-text-3">
                                                Design</h4>
                                            <h3 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-4-base u-text-4">
                                                <span style="font-size: 2.25rem;">{{ price.price }} руб.</span>
                                            </h3>
                                            <h6 class="u-custom-font u-font-pt-sans u-text u-text-default u-text-palette-4-base u-text-5">
                                                Heading Here</h6>
                                            <div class="u-border-1 u-border-grey-25 u-expanded-width u-line u-line-horizontal u-line-1"></div>
                                            <p class="u-text u-text-grey-50 u-text-6">{{ price.name }}</p>
                                            <div class="u-border-1 u-border-grey-25 u-expanded-width u-line u-line-horizontal u-line-2"></div>
                                            <p class="u-text u-text-grey-50 u-text-7">{{ price.description }}</p>
                                            <div class="u-border-1 u-border-grey-25 u-expanded-width u-line u-line-horizontal u-line-4"></div>
                                            {% if autentic %}
                                                <a href="{% url 'profile:pay_service' price.id %}"
                                                   class="u-active-palette-4-base u-border-2 u-border-palette-4-base u-btn u-button-style u-hover-palette-4-base u-none u-text-active-white u-text-hover-white u-text-palette-4-base u-btn-1">
                                                    Купить
                                            {% else %}
                                                <a href="{% url 'profile:login' %}"
                                                   class="u-active-palette-4-base u-border-2 u-border-palette-4-base u-btn u-button-style u-hover-palette-4-base u-none u-text-active-white u-text-hover-white u-text-palette-4-base u-btn-1">
                                                    Купить
                                            {% endif %}

                                      <span class="u-icon u-icon-1">
                                          <svg class="u-svg-content" viewBox="0 0 492.004 492.004" x="0px" y="0px"
                                               style="width: 1em; height: 1em;">
                                              <g>
                                                  <g>
                                                      <path d="M484.14,226.886L306.46,49.202c-5.072-5.072-11.832-7.856-19.04-7.856c-7.216,0-13.972,2.788-19.044,7.856l-16.132,16.136
                                                         c-5.068,5.064-7.86,11.828-7.86,19.04c0,7.208,2.792,14.2,7.86,19.264L355.9,207.526H26.58C11.732,207.526,0,219.15,0,234.002
                                                            v22.812c0,14.852,11.732,27.648,26.58,27.648h330.496L252.248,388.926c-5.068,5.072-7.86,11.652-7.86,18.864
                                                              c0,7.204,2.792,13.88,7.86,18.948l16.132,16.084c5.072,5.072,11.828,7.836,19.044,7.836c7.208,0,13.968-2.8,19.04-7.872
                                                                l177.68-177.68c5.084-5.088,7.88-11.88,7.86-19.1C492.02,238.762,489.228,231.966,484.14,226.886z"></path>
                                                  </g>
                                              </g>
                                          </svg>
                                      </span>&nbsp;<br>
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>




    <section data-bs-version="5.1" class="article8 cid-tT4ZBrVYs7" id="article08-8">


        <div class="container">
            <div class="row justify-content-center" style="max-width: 100%; height: auto;">
                {% for post in posts %}
                    <a class="card col-md-12 col-lg-10">
                    {%  if autentic %}
                        <a href="{% url 'profile:post_detailed' post.id %}">
                            <div class="card-wrapper">
                                <div class="image-wrapper d-flex justify-content-center mb-4 ">
                                    <img src="
                                            {% if post.images %}{{ post.images.url }}{% else %}{% static 'image/profile_img/img.png' %}{% endif %}"
                                         alt="Mobirise Website Builder" style="max-width: 100%; height: auto;">
                                </div>
                                <div class="card-content-text">
                                    <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2">
                                        <strong>{{ post.title }}</strong>
                                    </h3>
                                    <div class="row card-box align-left">
                                        <div class="item features-without-image col-12">
                                            <div class="item-wrapper">
                                                <p class="mbr-text mbr-fonts-style display-7">
                                                    {{ post.content|safe }}
                                                </p>
                                                <p class="mbr-text mbr-fonts-style display-7">
                                                    {{ post.date_create }}
                                                </p>
                                                {% if teach %}
                                                    <a href="{% url 'profile:delete_post' post.id %}">
                                                        <button class="btn btn-primary">
                                                            <i class="bi bi-cart-fill"></i> Удалить
                                                        </button>
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% else %}
                        <a href="#">
                            <div class="card-wrapper">
                                <div class="image-wrapper d-flex justify-content-center mb-4 ">
                                    <img src="{% if post.images %}{{ post.images.url }}{% else %}{% static 'image/profile_img/img.png' %}{% endif %}"
                                         alt="Mobirise Website Builder" style="max-width: 100%; height: auto;">
                                </div>
                                <div class="card-content-text">
                                    <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2">
                                        <strong>{{ post.title }}</strong>
                                    </h3>
                                    <div class="row card-box align-left">
                                        <div class="item features-without-image col-12">
                                            <div class="item-wrapper">
                                                <p class="mbr-text mbr-fonts-style display-7">
                                                    {{ post.content|safe }}
                                                </p>
                                                <p class="mbr-text mbr-fonts-style display-7">
                                                    {{ post.date_create }}
                                                </p>
                                                {% if teach %}
                                                    <a href="{% url 'profile:delete_post' post.id %}">
                                                        <button class="btn btn-primary">
                                                            <i class="bi bi-cart-fill"></i> Удалить
                                                        </button>
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="display-7"
    <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
    <script src="{% static 'assets/ytplayer/index.js' %}"></script>
    <script src="{% static 'assets/dropdown/js/navbar-dropdown.js' %}"></script>
    <script src="{% static 'assets/theme/js/script.js' %}"></script>


{% endblock %}