SmartLearn/CabinetApp/urls.py
from django.urls import path
from .views import get_events, cabinets_view, update_calend, user_full, user_full_view, VideoArchView

app_name = 'cabinet'


urlpatterns = [
    path('get_events/<int:cabinet_id>/', get_events, name='get_events'),
    path('cabinets/<int:cab_id>/', cabinets_view, name='cabinet'),
    path('get_updates/<int:cabinet_id>/', update_calend, name='get_update'),
    path('userfull_info_cab/<int:cabinet_id>/', user_full, name='userfull_info_cab'),
    path('userfull_detailed/<int:post_id>/', user_full_view, name='userfull_detailed'),
    path('records_cab/<int:cabinet_id>/', VideoArchView.as_view(), name='records_cab')
]

SmartLearn/ChatApp/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path('', views.chat, name="chat"),
    path("<int:chat_id>/", views.room, name="room"),
    path('create_chat_d/<int:another_user_id>/', views.create_chat_dialog, name="create_chat"),
]

SmartLearn/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ProfileApp.views import IndexView



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('cabinet/', include('CabinetApp.urls', namespace='сabinet')),
    path('profile/', include('ProfileApp.urls', namespace='profile')),
    path("chat/", include("ChatApp.urls")),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SmartLearn/SmartLearn/urls.py
from django.contrib import admin
from django.urls import path, include
from SmartLearn.Learn.views import *

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('Learn.urls', namespace='Learn')),
]

SmartLearn/CabinetApp/models.py
from django.db import models

from ProfileApp.models import Teacher, User
from django.utils.timezone import now

# Create your models here.


class Cabinet(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='cabinets', null=True, blank=True)
    users = models.ManyToManyField(User, related_name='cabinets')
    user_count = models.IntegerField(null=True, blank=True)



    def __str__(self):
        return self.name


class Schedule(models.Model):
    cabinet = models.ForeignKey('Cabinet', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    url = models.URLField()
    date_create = models.DateTimeField(null=True, blank=True)
    date_end = models.DateTimeField(null=True, blank=True)
    an_dellet = models.BooleanField(default=False)

    def time_end(self):
        return now() > self.date_end if self.date_end else False


class Record(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='record_teacher')
    date_create = models.DateTimeField(auto_now_add=True)
    cabinet = models.ForeignKey(Cabinet, on_delete=models.CASCADE, related_name='record_cabinets')

    def __str__(self):
        return self.url

SmartLearn/CabinetApp/forms.py
from django import forms
from CabinetApp.models import Record

class RecordsForms(forms.ModelForm):
    title = forms.CharField()
    url = forms.URLField()

    class Meta:
        model = Record
        fields = ['title', 'url', 'cabinet']

SmartLearn/CabinetApp/views.py
import asyncio

from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from icecream import ic
from django.utils import timezone

from CabinetApp.forms import RecordsForms
from CabinetApp.models import Cabinet, Schedule, Record
from CabinetApp.scrapper import starting_pars
from ProfileApp.models import User, Post
from django.views import View


# Create your views her
def get_events(request, cabinet_id):
    cabinet = Cabinet.objects.get(id=cabinet_id)
    now = timezone.now()
    Schedule.objects.filter(cabinet=cabinet, date_end__lt=now).delete()

    events = Schedule.objects.filter(cabinet=cabinet).values('date_create', 'date_end', 'url', 'title')
    event_data = []
    for event in events:
        event_data.append({
            'title': event['title'],
            'urls': event['url'],
            'start': event['date_create'].isoformat(),
            'end': event['date_end'].isoformat() if event['date_end'] else None,
        })
    return JsonResponse(event_data, safe=False)


# def calendar_view(request: HttpRequest) -> render:
#     return render(request, 'CabinetApp/calend.html')


def cabinets_view(request: HttpRequest, cab_id: int) -> render:
    if request.user.id:
        pers = User.objects.get(id=request.user.id).is_authenticated
    else:
        pers = False
    print(pers)
    context = {
        'title': 'Кабинеты',
        'cabinet_id': cab_id,
        'autentic': pers,
    }
    return render(request, 'Cabinet/cabinet.html', context=context)


def update_calend(request: HttpRequest, cabinet_id) -> render:
    if request.method == 'POST':
        date_string = request.POST
        print(date_string)
        if date_string:
            cabinet = Cabinet.objects.get(pk=cabinet_id)
            schedule = Schedule.objects.create(
                cabinet=cabinet,
                title=date_string['title'],
                url=date_string['urls'],
                date_create=date_string['start'],
                date_end=date_string['end'],
            )
            print(schedule)
            schedule.save()

            return redirect('cabinet:cabinet', cab_id=cabinet_id)


def user_full(request: HttpRequest, cabinet_id) -> render:
    if request.user.id:
        pers = User.objects.get(id=request.user.id)
    else:
        pers = False
    teachs = Cabinet.objects.get(pk=cabinet_id).teacher
    post = Post.objects.filter(teacher=teachs, is_private=True).order_by('-date_create')
    context = {
        'title': 'Полезная информация',
        'autentic': pers.is_authenticated,
        'teach': teachs,
        'user_id': pers.id,
        'posts': post,
        'cabinet_id': cabinet_id,
    }
    return render(request, 'Cabinet/userfull_info_cab.html', context=context)


class VideoArchView(View):

    def get(self, request, cabinet_id):
        form = RecordsForms()
        if request.user.id:
            pers = User.objects.get(id=request.user.id)
        else:
            pers = False
        cabinet = Cabinet.objects.get(pk=cabinet_id)
        teachs = cabinet.teacher
        records = Record.objects.filter(cabinet=cabinet)
        context = {
            'title': 'Архив записей видео',
            'autentic': pers.is_authenticated,
            'teach': teachs,
            'user_id': pers.id,
            'records': records,
            'cabinet_id': cabinet_id,
            'form': form,
        }
        return render(request, 'Cabinet/records.html', context=context)

    def post(self, request, cabinet_id):
        form = RecordsForms(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            url = form.cleaned_data['url']
            cabinet = Cabinet.objects.get(pk=cabinet_id)
            record = Record.objects.create(title=title, url=url, cabinet=cabinet, teacher=cabinet.teacher)
            record.save()
            return redirect('cabinet:records_cab', cabinet_id=cabinet_id)


def user_full_view(request: HttpRequest, post_id: int) -> render:
    if request.user.id:
        pers = User.objects.get(id=request.user.id)
    else:
        pers = False
    post = Post.objects.get(id=post_id)
    context = {
        'title': 'Полезная информация',
        'user_id': pers.id,
        'autentic': pers.is_authenticated,
        'posts': post,
    }
    return render(request, 'Cabinet/userfull_detailed.html', context=context)

SmartLearn/CabinetApp/templates/Cabinet/base_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="theme-color" content="#478ac9">
    <meta property="og:type" content="website">
    <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/@fullcalendar/core/main.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">

    <!-- Подключение JavaScript-файлов Bootstrap (перед закрывающимhttps://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.jsся тегом </body>) -->
    <link rel="stylesheet" href="{% static 'userfull/css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'userfull/css/Главная.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'userfull/css/Страница-1.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'userfull/scripts/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'userfull/scripts/nicepage.js' %}" defer=""></script
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        .navbar-nav.mr-auto .nav-item {
            margin-right: -50px; /* Убираем правый отступ между элементами */
        }
        .card-body {
          padding: 10px;
        }
        .card-text {
          overflow: hidden;
          text-overflow: ellipsis;
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
        }
    </style>
    {% block scripts %}{% endblock %}
    {% block styles %}{% endblock %}
    {% block modals %}{% endblock %}
</head>
<body>
    <header>
        <!-- Шапка сайта -->

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">главная</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
{% block content %}{% endblock %}
{% block script %}{% endblock %}
    <footer>
        <!-- Футер сайта -->
        <p>&copy; 2023 Мой учебный сайт</p>
    </footer>
</body>
</html>

SmartLearn/CabinetApp/templates/Cabinet/cabinet.html
{% extends 'profileapp/profile/base_cabinet_index.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core/main.js"></script>
    <script src="{% static 'fullcalendar/dist/index.global.js' %}"></script>
    <script>
        var getEventsURL = "{% url 'cabinet:get_events' cabinet_id %}";
        var getUrl = "{% url 'cabinet:get_update' cabinet_id %}";
    </script>
{% endblock %}
{% block styles %}
    <style>
        .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }

                .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }
    </style>
{% endblock %}

{% block modals %}

{% endblock %}
{% block url %}
{#<li class="nav-item"><a class="nav-link py-3 border-bottom rounded-0" href="{%  url 'cabinet:userfull_info_cab' cabinet_id %}">Полезные материалы</a>#}
{#            </li>#}
{#<li class="nav-item"><a class="nav-link py-3 border-bottom rounded-0" href="{%  url 'cabinet:userfull_info_cab' cabinet_id %}">Полезные материалы</a>#}
{#            </li>#}
{% endblock %}
{% block content %}

    {% include 'Cabinet/calend.html' %}

{% endblock %}
{% block script %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>{% endblock %}

SmartLearn/CabinetApp/templates/Cabinet/calend.html
    <div class="container my-4">
        <div id='calendar' class="p-3"></div>
    </div>
    {% csrf_token %}
        <div id="eventDataDialog" style="display: none;">
            <label for="eventData">Информация о событии:</label>
            <input type="text" id="eventData" />
            <label for="urls">Ссылка:</label>
            <input type="text" id="urls" />
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var calendarEl = document.getElementById('calendar');
                var calendar = new FullCalendar.Calendar(calendarEl, {
                    headerToolbar: {
                        left: 'prevYear,prev,next,nextYear today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                    },
                    initialDate: new Date(),
                    navLinks: true,
                    editable: true,
                    dayMaxEvents: true,
                    selectable: true,
                    selectMirror: true,
                    events: getEventsURL,
                    eventClick: function(info) {
                        // Получите ссылку из события
                        var url = info.event.extendedProps.urls;

                        // Переход на страницу по ссылке
                        window.location.href = url;
                    },
                    select: function(info) {
                        var eventData = prompt('Введите информацию о событии:');
                        var urlsData = prompt('Введите ссылку на занятие:');

                        var csrfToken = $('input[name=csrfmiddlewaretoken]').val();
                        if (eventData) {
                            $.ajax({
                                url: getUrl, // Замените на URL для сохранения события в базе данных
                                type: 'POST',
                                data: {
                                    csrfmiddlewaretoken: csrfToken,
                                    title: eventData,
                                    urls: urlsData,
                                    start: info.startStr,
                                    end: info.endStr
                                },
                                success: function(response) {
                                    // Обновить календарь, получив новые события с getEventsURL
                                    calendar.refetchEvents();
                                }
                            });
                        }
                    },
                    // Установите формат времени
                    locale: 'ru',
                    timeFormat: 'H:mm'
                });

                calendar.render();
            });
        </script>

SmartLearn/CabinetApp/templates/Cabinet/parsing.html
{% extends 'profileapp/profile/base_cabinet_index.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}
{% block scripts %}
{% endblock %}
{% block styles %}
{% endblock %}

{% block modals %}

{% endblock %}
{% block url %}
{% endblock %}
{% block content %}
    <h1>Поиск</h1>
    <form action="{% url 'cabinet:parsing' %}" method="POST">
    {% csrf_token %}
        <label for="search">Введите ваш запрос:</label>
        <input type="text" id="answer" name="answer" placeholder="Поиск..." required>
        <input type="submit" value="Искать">
    </form>
    <div class="container">
        <div class="row">
            {% if result != None %}
                {% for work in result %}
                    {% for woo in work %}
                        <h1><p style="atsc-dynamic-refresh: true">{{ work.description }}</p></h1>

                        <p style="atsc-dynamic-refresh: true">{{ work.web }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>




{% endblock %}
{% block script %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>{% endblock %}

SmartLearn/CabinetApp/templates/Cabinet/records.html
{% extends 'profileapp/profile/base_cabinet_index.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core/main.js"></script>
    <script src="{% static 'fullcalendar/dist/index.global.js' %}"></script>
{% endblock %}
{% block styles %}
    <style>
        .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }

                .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }
    </style>
{% endblock %}

{% block modals %}

{% endblock %}

{% block content %}
    {% if user.is_teacher %}
        <div class="container">
            <div class="row">
                <div class="col-md-3">
            <form method="post" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить">
            </form>
        </div>
   {% endif %}
<div class="container my-4">
   <section class="u-clearfix u-section-1" id="sec-969d">
      <div class="u-clearfix u-sheet u-sheet-1"><!--blog--><!--blog_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/blog_options_json-->
        <div class="u-blog u-expanded-width u-blog-1">
          <div class="u-repeater u-repeater-1"><!--blog_post-->
            {% for record in records %}
                <div class="col-md-12">
                        <div class="card mb-3"">
                            <div class="card-body d-flex flex-row align-items-center">
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <a href="{{ record.url }}">
                                            <p class="card-text text-wrap">{{ record.title }}</p>
                                            <p class="card-text text-wrap">{{ record.date_create }}</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div><!--/blog-->
  </div>
</section>
<section class="u-clearfix u-section-2" id="sec-d944">
  <div class="u-clearfix u-sheet u-valign-middle u-sheet-1"></div>
</section>

{% endblock %}
{% block script %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>{% endblock %}

SmartLearn/CabinetApp/templates/Cabinet/userfull_info_cab.html
{% extends 'profileapp/profile/base_cabinet_index.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core/main.js"></script>
    <script src="{% static 'fullcalendar/dist/index.global.js' %}"></script>
{% endblock %}
{% block styles %}
    <style>
        .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }

                .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #333; /* Цвет фона */
            padding-top: 20px;
            z-index: 1; /* Устанавливаем z-index для боковой панели */
        }

        /* Стили для пунктов меню */
        .sidenav a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 18px;
            color: #fff; /* Цвет текста */
            display: block;
        }

        /* Стили для активного пункта меню */
        .sidenav a.active {
            background-color: #4CAF50; /* Цвет активного пункта */
        }

        /* Стили для контента, сдвигаемого вправо */
        .content {
            margin-left: 250px; /* Ширина боковой панели */
            padding: 20px;
            z-index: 1; /* Устанавливаем z-index для контента */
        }
    </style>
{% endblock %}

{% block modals %}

{% endblock %}

{% block content %}
<div class="container my-4">
   <section class="u-clearfix u-section-1" id="sec-969d">
      <div class="u-clearfix u-sheet u-sheet-1"><!--blog--><!--blog_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/blog_options_json-->
        <div class="u-blog u-expanded-width u-blog-1">
          <div class="u-repeater u-repeater-1"><!--blog_post-->
            {% for post in posts %}
                <div class="col-md-12">
                        <div class="card mb-3"">
                            <div class="card-body d-flex flex-row align-items-center">
                                <div class="col-md-4">
                                    <img src="{% if post.images %}{{ post.images.url }}{% else %}{% static 'image/profile_img/img.png' %}{% endif %}" class="card-img img-fluid w-100" alt="Учитель">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <a href="{% url 'cabinet:userfull_detailed' post.id %}">
                                            <p class="card-text text-wrap">{{ post.title }}</p>
                                            <p class="card-text text-wrap">{{ post.date_create }}</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div><!--/blog-->
  </div>
</section>
<section class="u-clearfix u-section-2" id="sec-d944">
  <div class="u-clearfix u-sheet u-valign-middle u-sheet-1"></div>
</section>

{% endblock %}
{% block script %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>{% endblock %}